version: '3.8'

volumes:
  pg_app:

services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security_aws_db_docker
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - pg_app:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    image: webfluxapp
    ports:
      - 8080:8080
    environment:
      SPRING_R2DBC_URL: r2dbc:pool:mysql://db:3306/security_aws_db_docker?autoReconnect=true&useSSL=false
      SPRING_R2DBC_USERNAME: admin
      SPRING_R2DBC_PASSWORD: root
    depends_on:
      - db